const Map<String, String> arTranslation = {
  "welcome": "مرحبا",
  "welcomeTitle": "مرحبا بكم",
  "welcomeBody": "هنا نقدم لكم ارشادات ونصائح حول الحميات الصحية لمساعدتك في تحقيق أهدافك الصحية.",
  "exit": "خروج",
  "language": "اللغة",
  "splash": "انتظر...",
  "login": "تسجيل الدخول",
  "enterUserName": "ادخل اسم المستخدم",
  "username": "اسم المستخدم",
  "hintPassword": "ادخل كلمة السر",
  "password": "كلمة السر",
  "dont_have_account": " ليس لدي حساب",
  "dontHaveAccountQuestion": "ليس لديك حساب؟ ",
  "createAccountAction": "قم بإنشاء حساب",
  "enterPersonalEmail": "ادخل الايميل الشخصي",
  "alreadyHaveAccountQuestion": "لديك حساب بالفعل ؟ ",
  "loginAction": "قم بتسجيل دخول",
  "asUser": "كمستخدم",
  "asDoctor": "كطبيب",
  "enterNameShort": "ادخل الإسم",
  "confirmPasswordAction": "قم بتأكيد كلمة السر",
  "enterDietPrice": "ادخل سعر الحمية",
  "enterBankAccount": "ادخل الحساب البنكي",
  "academicDegree": "الدرجة العلمية",
  "cvBio": "السيرة الذاتية",
  "signup": "انشاء حساب",
  "forget_password": "نسيت كلمة السر",
  'forgotPasswordTitle': 'نسيت كلمة المرور',
  'verifyEmailTitle': 'تحقق من الإيميل',
  'verificationCode': 'كود التحقق',
  'verificationCodeSentTo': 'تم إرسال كود التحقق الى',
  'verify': 'تحقق',
  'goBack': 'تراجع',
  'verifyCodeRequired': 'يرجى إدخال كود التحقق',
  'verifyFailed': 'فشل التحقق',
  'emailVerified': 'تم التحقق من البريد الإلكتروني بنجاح',
  'verificationCodeResent': 'تم إعادة إرسال كود التحقق إلى بريدك الإلكتروني',
  'resendCode': 'إعادة إرسال الكود',
  'email': 'البريد الإلكتروني',
  'enterYourEmail': 'أدخل البريد الإلكتروني',
  'sendResetLink': 'إرسال رابط إعادة التعيين',
  'pleaseWait': 'يرجى الانتظار...',
  // signup
  'signupTitle': 'إنشاء حساب',
  'signupButton': 'تسجيل',

  // fields
  'name': 'الاسم',
  'enterName': 'أدخل الاسم',
  'enterEmail': 'أدخل البريد الإلكتروني',
  'phoneOptional': 'رقم الهاتف (اختياري)',
  'enterPhone': 'أدخل رقم الهاتف',

  // role
  'roleOptional': 'الدور (اختياري)',
  'selectRole': 'اختر الدور',
  'patient': 'مريض',
  'doctor': 'طبيب',

  'passwordHint': '8 أحرف على الأقل',
  'confirmPassword': 'تأكيد كلمة المرور',
  'confirmPasswordHint': 'أعد إدخال كلمة المرور',

  "homeTitle": "الصفحة الرئيسية",
  "settings": "الإعدادات",
  "personalAccount": "الحساب الشخصي",
  "remindersAlerts": "تذكيرات ومنبهات",
  "team": "فريق العمل",
  "editProfile": "تعديل الملف الشخصي",
  "enterPassword": "ادخل كلمة السر",
  "addReminder": "إضافة تذكير",
  "reminderTime": "وقت التذكير",
  "save": "حفظ",
  "close": "اغلاق",
  "personalPatientInfo": "معلومات المريض الشخصية",
  "diets": "الحميات",
  "chat": "الدردشة",
  "reports": "التقارير",
  "bodyCalculations": "حسابات الجسم",
  "medicalExaminations": "الفحوصات الطبية",
  "helpFiles": "ملفات مساعدة",
  "mainMenu": "القائمة الرئيسة",
  "edit": "تعديل",
  "delete": "حذف",
  "noReminders": "لا توجد تذكيرات بعد. اضغط إضافة تذكير لإنشاء واحد.",
  "stepCounter": "عداد الخطوات",
  "startCounting": "بدء العد",
  "step": "خطوة",
  "steps": "خطوات",
  "stepCounterPermissionDenied": "يجب السماح بتتبع النشاط لعد الخطوات",
  "spiritualNutrition": "التغذية الروحية",
  "morningAthkar": "أذكار الصباح",
  "eveningAthkar": "أذكار المساء",
  "athkar": "الأذكار",
  "noAthkarFound": "لا توجد أذكار",
  "comingSoon": "قريباً",
  "doctorsList": "قائمة الأطباء",
  "doctorsListDesc": "تصفح الأطباء المتاحين",
  "tips": "النصائح",
  "tipsDesc": "نصائح وإرشادات صحية",
  "tipsIntro": "العديد من النصائح الطبية التغذوية المفيدة لك!",
  "tipsGeneral": "نصائح تغذوية عامة",
  "tipsSports": "نصائح رياضية",
  "tipsMyths": "خرافات تغذوية",
  "noTipsFound": "لا توجد نصائح",
  "bmiCalc": "حساب BMI",
  "bmiCalcDesc": "احسب مؤشر كتلة الجسم بسرعة",
  "phone": "الهاتف",
  "role": "الدور",
  "logout": "تسجيل الخروج",
  "yourPrivateClinic": "عيادتك الخاصة",
  "welcomeToClinic": "مرحبا بك",
  "welcomeToClinicSub": "في عيادتك الخاصة",
  "patientsList": "قائمة المرضى",
  "searchForPatient": "ابحث عن مريضك",
  "patientInformation": "معلومات المريض",
  "nutritionalCalculations": "الحسابات التغذوية",
  "proteinFatCarbs": "نسبة البروتين والدهون والكربوهيدرات",
  "patientName": "اسم المريض",
  "patientAge": "عمر المريض",
  "patientGender": "جنس المريض",
  "patientPhone": "رقم هاتف المريض",
  "saveChanges": "حفظ التعديل",
  "servingsInGrams": "عدد الحصص بالجرام",
  "physicalActivityLevel": "النشاط الحركي",
  "calories": "السعرات الحرارية",
  "bmr": "BMR",
  "noInternet": "لا يوجد اتصال بالإنترنت",
  "serverError": "خطأ في الخادم",
  "retry": "إعادة المحاولة",
  "refresh": "تحديث",
  "noDoctors": "لا يوجد أطباء حالياً",
  "available": "متاح",
  "notAvailable": "غير متاح",
  "verified": "موثّق",
  "notVerified": "غير موثّق",
  "rating": "التقييم",
  "experience": "الخبرة",
  "years": "سنوات",
  "fee": "الأجرة",
  "heightCm": "الطول (سم)",
  "heightHint": "أدخل الطول بالسنتيمتر",
  "weightKg": "الوزن (كجم)",
  "weightHint": "أدخل الوزن بالكيلوجرام",
  "calculate": "احسب",
  "bmiResult": "مؤشر كتلة الجسم",
  "bmiUnder": "نقص في الوزن",
  "bmiNormal": "وزن طبيعي",
  "bmiOver": "زيادة في الوزن",
  "bmiObese": "سمنة",
  "error": "خطأ",
  "enterHeightWeight": "يرجى إدخال الطول والوزن",
  "invalidValues": "قيم غير صحيحة",

  "doctorDetails": "تفاصيل الطبيب",
  "personalEmail": "الإيميل الشخصي",
  "bankAccount": "الحساب البنكي",
  "dietPrice": "سعر الحمية",
  "choosePlan": "اختر الخطة",
  "basicPlan": "أساسي",
  "premiumPlan": "مميز",
  "months": "شهر",
  "subscribe": "اشتراك",

  "gender": "الجنس",
  "degree": "المؤهل",
  "specialization": "التخصص",
  "license": "رقم الترخيص",
  "consultationFee": "رسوم الاستشارة",
  "bio": "نبذة",
  "success": "تم",
  "ok": "موافق",
  "sessionExpired": "انتهت الجلسة، سجل الدخول مرة أخرى",
  "subscribeFailed": "فشل الاشتراك، حاول مرة أخرى",
  "subscriptionCreated": "تم إنشاء الاشتراك بنجاح",
  "virtual_payment": "الدفع الافتراضي",
  "payment_card": "بطاقة",
  "payment_cash": "نقداً",
  "payment_wallet": "محفظة",
  "summary_plan": "الخطة",
  "summary_duration": "المدة",
  "summary_price": "السعر",
  "pay_and_subscribe": "ادفع واشترك",

  "payment_transfer": "حوالة",

// Card
  "card_info": "بيانات البطاقة",
  "card_holder": "اسم حامل البطاقة",
  "card_holder_hint": "الاسم المكتوب على البطاقة",
  "card_number": "رقم البطاقة",
  "card_number_hint": "**** **** **** ****",
  "card_exp": "تاريخ الانتهاء",
  "card_exp_hint": "MM/YY",
  "card_cvv": "رمز CVV",
  "card_cvv_hint": "***",

// Wallet
  "wallet_info": "بيانات المحفظة",
  "wallet_name": "اسم المحفظة",
  "wallet_name_hint": "مثال: يمن باي",
  "wallet_number": "رقم المحفظة",
  "wallet_number_hint": "رقم الهاتف أو الحساب",
  "wallet_ref": "رقم العملية",
  "wallet_ref_hint": "رقم أو مرجع العملية",

// Transfer
  "transfer_info": "بيانات الحوالة",
  "transfer_sender": "اسم المُرسل",
  "transfer_sender_hint": "اسم الشخص المُرسل",
  "transfer_receiver": "اسم المُستلم",
  "transfer_receiver_hint": "اسم الشخص المُستلم",
  "transfer_ref": "رقم الحوالة",
  "transfer_ref_hint": "رقم أو مرجع الحوالة",
  "transfer_amount": "مبلغ الحوالة",
  "transfer_amount_hint": "أدخل المبلغ",
  "login_failed":"فشل الدخول",
  "male":"ذكر",
  "female":"انثى",
  "results":"النتيجة",
  "age":"العمر",
  // العناوين العامة
  "bmiBmrCalc": "حاسبة الوزن والسعرات العلاجية",
  "enterData": "إدخال البيانات الحيوية",

  "kcalPerDay": "سعرة/يوم",

  // حقول الإدخال

  "ageHint": "مثال: 25",


  // مستويات النشاط (حسب الورقة)
  "activityLevel": "مستوى النشاط البدني",
  "activitySedentary": "خامل (لا يوجد نشاط)",
  "activityLow": "نشاط منخفض",
  "activityModerate": "نشاط متوسط",
  "activityVery": "نشاط عالي جداً",
  "activityExtra": "نشاط رياضي شاق",


  "bmiObese1": "سمنة درجة أولى (Class I)",
  "bmiObese2": "سمنة درجة ثانية (Class II)",
  "bmiObese3": "سمنة مفرطة (Class III)",

  "enterAllFields": "يرجى إدخال جميع البيانات",


  "completeProfile": "أكمل بياناتك",

  "dateOfBirth": "تاريخ الميلاد",

  "physicalActivity": "النشاط البدني",
  "sedentary": "خامل",
  "low": "نشاط منخفض",
  "active": "نشاط متوسط",
  "veryActive": "نشاط عالي",
  "medicalHistory": "التاريخ المرضي",
  "profileSaved": "تم حفظ البيانات بنجاح",
  "fillFields": "يرجى تعبئة الحقول المطلوبة بشكل صحيح",

  // forums
  "forums": "المنتديات",
  "forumsDesc": "شارك في النقاشات مع الآخرين",
  "noForums": "لا توجد منتديات حالياً",
  "forumPosts": "المنشورات",
  "noPosts": "لا توجد منشورات بعد",
  "joinForum": "انضمام",
  "writePost": "اكتب المحتوى...",
  "postTitle": "عنوان المنشور",
  "fillPostFields": "يرجى تعبئة العنوان والمحتوى",

  // consultations
  "consultations": "الاستشارات",
  "consultationsDesc": "حجز استشارات مع الأطباء",
  "noConsultations": "لا توجد استشارات",
  "requestConsultation": "طلب استشارة",
  "doctorId": "معرف الطبيب",
  "consultationType": "نوع الاستشارة",
  "initialConsultation": "استشارة أولية",
  "followUp": "متابعة",
  "review": "مراجعة",
  "scheduledDate": "التاريخ والوقت",
  "request": "طلب",
  "cancel": "إلغاء",

  // diet
  "myDiet": "حميتي",
  "myDietDesc": "عرض خطة الحمية والوجبات الحالية",
  "subscribedFeatures": "مميزات المشتركين",
  "noDiet": "لا توجد خطة حمية نشطة",
  "dietMeals": "وجبات الحمية",
  "viewMeals": "عرض الوجبات",
  "noMeals": "لا توجد وجبات",
  "createDietPlan": "إنشاء خطة حمية",
  "patientId": "معرف المريض",
  "dailyCalories": "السعرات اليومية",
  "durationDays": "المدة (بالأيام)",
  "startDate": "تاريخ البدء",
  "endDate": "تاريخ الانتهاء",
  "create": "إنشاء",
  "you": "أنت",
  "saved": "تم الحفظ بنجاح",
  "remove": "إزالة",
  "nutritionMacros": "التغذية (كربوهيدرات، دهون، بروتين)",
  "carbohydrates": "الكربوهيدرات",
  "fats": "الدهون",
  "protein": "البروتين",
  "createDietForPatient": "إنشاء حمية للمريض",











};
